name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set short_ref
        id: sha
        run: echo ::set-output name=value::${GITHUB_REF#refs/*/}
      - name: Set short_sha
        id: ref
        run: echo ::set-output name=value::$(git rev-parse --short HEAD)
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: movexif-${{ steps.ref.outputs.value }}-${{steps.sha.outputs.value}}
          path: "dist/"