name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set short_ref
        id: vars
        run: echo ::set-output name=ref::${GITHUB_REF#refs/*/}
      - name: Set short_sha
        id: vars
        run: echo ::set-output name=sha::$(git rev-parse --short HEAD)
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: movexif-${{ steps.vars.outputs.ref }}-${{steps.vars.outputs.sha}}
          path: "dist/"