name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: movexif-${{ env.GITHUB_REF }}-${{ env.GITHUB_SHA::8 }}
          path: "dist/"